stages:
  - build

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

.mappy_branch_only: &mappy_branch_rules
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "mappy"'


build_mapbox_gl:
  stage: build
  script:
    - sh scripts/build_and_archive_for_mappy_jenkins.sh dynamic
    - mkdir -p pkg/
    - mv build/ios/mapbox-ios-sdk-dynamic.zip pkg/
  rules: *mappy_branch_rules
  artifacts:
    paths:
      - pkg/mapbox-ios-sdk-dynamic.zip
    expire_in: 2 months
