stages:
  - build
  - promote

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

.mappy_branch_only: &mappy_branch_rules
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "mappy"'

.manual_job_rules: &mappy_branch_manual_rules
  - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "mappy"'
    when: manual


build_mapbox_gl:
  stage: build
  script:
    - echo "BUILD_JOB_ID=$CI_JOB_ID" >> build.env
    - sh scripts/build_and_archive_for_mappy_jenkins.sh dynamic
    - mkdir -p pkg/
    - mv build/ios/mapbox-ios-sdk-dynamic.zip pkg/
  rules: *mappy_branch_rules
  artifacts:
    paths:
      - pkg/mapbox-ios-sdk-dynamic.zip
    reports:
      dotenv: build.env
    expire_in: 2 months

promote_mapbox_gl:
  stage: promote
  script:
    - "curl -X POST -k -F token=$MAPPY_FMK_TRIGGER_TOKEN -F ref=master -F variables[MAPBOX_BUILD_JOB_ID]=$BUILD_JOB_ID $CI_API_V4_URL/projects/$MAPPY_FMK_PROJECT_ID/trigger/pipeline"
  rules: *mappy_branch_manual_rules
  needs:
    - job: build_mapbox_gl
      artifacts: true
